const fs = require("fs");
const path = require("path");

const repoArgIndex = process.argv.indexOf("--repo");
const repoPath =
  repoArgIndex !== -1 ? process.argv[repoArgIndex + 1] : process.env.MATERIAL_ICONS_REPO;

if (!repoPath) {
  console.error("Missing upstream repo path. Use --repo /path/to/material-design-icons or set MATERIAL_ICONS_REPO.");
  process.exit(1);
}

const styles = [
  { name: "rounded", upstreamDir: "materialsymbolsrounded" },
  { name: "outlined", upstreamDir: "materialsymbolsoutlined" },
  { name: "sharp", upstreamDir: "materialsymbolssharp" }
];

const sourceRoot = path.resolve(repoPath, "symbols", "web");
const outputRoot = path.resolve(__dirname, "..", "icons");
const allNames = new Set();

function isFill1File(fileName) {
  return fileName.toLowerCase().includes("fill1");
}

function isVariantFile(fileName) {
  return /_wght\d+/.test(fileName) || /_grad(?:N?\d+)/.test(fileName);
}

fs.mkdirSync(outputRoot, { recursive: true });

const iconDirs = fs
  .readdirSync(sourceRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name);

for (const style of styles) {
  const styleOutDir = path.join(outputRoot, style.name);

  fs.rmSync(styleOutDir, { recursive: true, force: true });
  fs.mkdirSync(styleOutDir, { recursive: true });

  let written = 0;

  for (const iconDir of iconDirs) {
    const styleDir = path.join(sourceRoot, iconDir, style.upstreamDir);

    if (!fs.existsSync(styleDir)) {
      continue;
    }

    const files = fs.readdirSync(styleDir);

    for (const fileName of files) {
      if (!fileName.endsWith("_24px.svg")) {
        continue;
      }

      if (isFill1File(fileName) || isVariantFile(fileName)) {
        continue;
      }

      const iconName = fileName.replace(/_24px\.svg$/, "");
      const srcPath = path.join(styleDir, fileName);
      const destPath = path.join(styleOutDir, `${iconName}.svg`);

      fs.copyFileSync(srcPath, destPath);
      allNames.add(iconName);
      written += 1;
    }
  }

  console.log(`${style.name}: wrote ${written} icons`);
}

const iconNames = Array.from(allNames).sort();
const indexJsPath = path.resolve(__dirname, "..", "index.js");
const indexDtsPath = path.resolve(__dirname, "..", "index.d.ts");

const indexJs = `// Auto-generated by scripts/generate-icons.js. Do not edit.\nconst ICON_NAMES = ${JSON.stringify(
  iconNames,
  null,
  2
)};\n\nmodule.exports = { ICON_NAMES };\n`;

const typeLines = iconNames.length
  ? iconNames.map((name) => `  | "${name}"`).join("\n")
  : "  | never";

const indexDts = `// Auto-generated by scripts/generate-icons.js. Do not edit.\nexport type IconName =\n${typeLines};\n\nexport declare const ICON_NAMES: readonly IconName[];\n`;

fs.writeFileSync(indexJsPath, indexJs, "utf8");
fs.writeFileSync(indexDtsPath, indexDts, "utf8");

console.log(`Generated ${iconNames.length} unique icon names`);
